title: Задачи
href: index.md
items: 
  - name: О задачах в Битрикс24
    href: index.md
  - name: Поля задачи
    href: fields.md
  - name: Добавить задачу
    href: tasks-task-add.md
  - name: Изменить задачу
    href: tasks-task-update.md
  - name: Получить задачу по идентификатору
    href: tasks-task-get.md
  - name: Получить список задач
    href: tasks-task-list.md
  - name: Прикрепить файлы к задаче
    href: tasks-task-files-attach.md
  - name: Принять задачу
    href: tasks-task-approve.md
  - name: Перевести задачу в статус «завершена»
    href: tasks-task-complete.md
  - name: Получить счетчики пользователя
    href: tasks-task-counters-get.md
  - name: Перевести задачу в статус «отложена»
    href: tasks-task-defer.md
  - name: Делегировать задачу
    href: tasks-task-delegate.md
  - name: Удалить задачу
    href: tasks-task-delete.md
  - name: Отклонить задачу
    href: tasks-task-disapprove.md
  - name: Добавить задачу в Избранное
    href: tasks-task-favorite-add.md
  - name: Удалить задачу из Избранного
    href: tasks-task-favorite-remove.md
  - name: Получить список полей
    href: tasks-task-get-fields.md
  - name: Проверить доступ к задаче
    href: tasks-task-get-access.md
  - name: История задачи
    href: tasks-task-history-list.md
  - name: Перевести задачу в статус «ждет выполнения»
    href: tasks-task-pause.md
  - name: Возобновить задачу после ее завершения
    href: tasks-task-renew.md
  - name: Перевести задачу в статус «выполняется»
    href: tasks-task-start.md
  - name: Включить наблюдение за задачей
    href: tasks-task-start-watch.md
  - name: Отключить наблюдение за задачей
    href: tasks-task-stop-watch.md
  - name: Включить режим «Без звука»
    href: tasks-task-mute.md
  - name: Отключить режим «Без звука»
    href: tasks-task-unmute.md
  - name: Создать связь между задачами
    href: task-dependence-add.md
  - name: Удалить связь между задачами
    href: task-dependence-delete.md
  - name: Результат задачи
    include:
      path: result/b24-toc.yaml
      mode: link
  - name: События
    include:
      path: events-tasks/b24-toc.yaml
      mode: link
  - name: Чек-листы
    include:
      path: checklist-item/b24-toc.yaml
      mode: link
  - name: Комментарии
    include:
      path: comment-item/b24-toc.yaml
      mode: link
  - name: Затраченное время
    include:
      path: elapsed-item/b24-toc.yaml
      mode: link
  - name: Пользовательские поля
    include:
      path: user-field/b24-toc.yaml
      mode: link
  - name: Стадии канбана и «Моего плана»
    include:
      path: stages/b24-toc.yaml
      mode: link
  - name: План рабочего дня
    include:
      path: planner/b24-toc.yaml
      mode: link
  - name: Потоки
    include:
      path: flow/b24-toc.yaml
      mode: link
  - name: Устаревшее
    include:
      path: deprecated/b24-toc.yaml
      mode: link